# Generated by Django 3.2.7 on 2021-09-30 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viajeros', '0001_initial'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_referencia_familiar', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=10)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje')),
                ('viajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajeros.viajero')),
            ],
        ),
    ]
