# Generated by Django 3.2.7 on 2021-09-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha_viaje',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='numero_plazas',
            field=models.CharField(max_length=22),
        ),
    ]
