# Generated by Django 3.2.7 on 2021-09-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_auto_20210930_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='numero_plazas',
            field=models.CharField(max_length=15),
        ),
    ]
